<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_presave().
 */
function adbt_debugging_node_presave(EntityInterface $node) {
  $title = $node->label();
  $node->title = $title . ' #Awesome!';
}

/**
 * Implements hook_theme().
 */
function adbt_debugging_theme($existing, $type, $theme, $path) {
  return [
    'creative_template' => [
      'variables' => ['type' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function adbt_debugging_preprocess_page(&$variables) {
  $user = $variables['user'];
}


/**
 * Implements hook_form_alter().
 */
function adbt_debugging_form_alter(&$form, FormStateInterface $form_state) {
  $method = $form['#method'];
}
