# Appserver overrides.
services:
  appserver:
    webroot: web
    xdebug: false
    config:
      php: .lando.php.ini
    overrides:
      environment:
        XDEBUG_MODE:

# Custom commands.
tooling:
 # Enable Xdebug.
 xdebug-on:
   service: appserver
   description: Enable xdebug for Apache.
   cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
   user: root
 # Disable Xdebug.
 xdebug-off:
   service: appserver
   description: Disable xdebug for Apache.
   cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
   user: root
